### ISSUE TITLE
Go over existing specs, document cases that are not covered.

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/michelson-semantics#280]

**Comment by nishantjr** [comment]
`DEXTER-ADDLIQUIDITY-NEGATIVE-SPEC` doesn't cover:                                                                      
                                                                                                                        
*  `notBool (Amount *Int TokenAmount) %Int XtzAmount =/=Int 0`                                                          
                                                                                                                        
`DEXTER-REMOVELIQUIDITY-NEGATIVE-SPEC` doesn't cover:                                                                   
                                                                                                                        
* `notBool (MinTokensWithdrawn <=Int (LqtBurned *Int TokenAmount) /Int OldLqt)`                                         
                                                                                                                        
These are covered because it occurs only when OldLqt < LqtBurned                                                        
* `notBool #IsLegalMutezValue((LqtBurned *Int XtzAmount) /Int OldLqt)`                                                  
* `notBool TokenAmount >=Int (LqtBurned *Int TokenAmount) /Int OldLqt`                                                  
* `notBool XtzAmount   >=Int (LqtBurned *Int   XtzAmount) /Int OldLqt`                                                  
                                                                                                                        
The following specs don't deal with target endpoing not existing                                                        
                                                                                                                        
- `DEXTER-ADDLIQUIDITY-POSITIVE-SPEC`                                                                                   
- `DEXTER-REMOVELIQUIDITY-NEGATIVE-SPEC`                                                                                
- `DEXTER-TOKENTOXTZ-FA*-NEGATIVE-*-SPEC`                                                                               
- `DEXTER-XTZTOTOKEN-FA*-NEGATIVE-*-SPEC`                                                                               
- `DEXTER-TOKENTOTOKEN-POSITIVE-SPEC`
